//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        
        [Required(ErrorMessage ="pls Enter Value")]
        [RegularExpression("^p+[0-9]{3}$", ErrorMessage = "Invalid Formate ")]
        public string pid { get; set; }
        [Required(ErrorMessage = "pls Enter Value")]
        [RegularExpression("^[a-z]+$",ErrorMessage ="Invalid Formate give only Alphabates")]
        public string pname { get; set; }
        [StringLength(10,ErrorMessage ="Exceeded length")]
        public string description { get; set; }
        [Required(ErrorMessage = "pls Enter Value")]
        [Range(1000,1000000,ErrorMessage ="Invalid range")]
        public Nullable<int> price { get; set; }
        
        [FileExtensions(Extensions ="jpg",ErrorMessage ="invalid file formate")]
        public string pimage { get; set; }
    }
}
